import fs from 'fs';
import path from 'path';
import readline from 'readline';
import { fileURLToPath } from 'url';
import {
  CODEX_SESSION_INDEX_PATH,
  CODEX_SESSIONS_DIR,
  CURSOR_COPILOT_WORKSPACE_STORAGE_DIR,
  CURSOR_PROJECTS_DIR,
  PROJECTS_DIR,
  VSCODE_COPILOT_WORKSPACE_STORAGE_DIR,
} from '../config.js';
import { getDb } from '../db/connection.js';
import type { CodexSessionIndexEntry } from '../types.js';
import {
  buildCursorComposerMetadataIndex,
  buildCursorComposerVirtualPath,
  listCursorComposerIdsWithBubbles,
  readCursorComposerConversation,
  readCursorWorkspaceState,
} from './cursor-state.js';
import { sanitizeConversationText } from './text-normalization.js';

const LOW_SIGNAL_PROMPT_RE = /^(untitled|no prompt|hi|hello|continue|缂備綀鍛暰|ok|濠靛倻鏅▓鎲掗柡鈧捄鍝勭厒)$/i;
const CAVEAT_PREFIX = 'Caveat: The messages below were generated by the user while running local commands.';
const CODEX_ID_PREFIX = 'codex-';
const COPILOT_ID_PREFIX = 'copilot-';
const SESSION_UPSERT_SQL = `
  INSERT INTO sessions (id, project_slug, project_path, summary, first_prompt, message_count,
    git_branch, model, created_at, modified_at, file_path, file_mtime,
    parent_session_id, is_subagent, codex_lineage_checked)
  VALUES (@id, @project_slug, @project_path, @summary, @first_prompt, @message_count,
    @git_branch, @model, @created_at, @modified_at, @file_path, @file_mtime,
    @parent_session_id, @is_subagent, @codex_lineage_checked)
  ON CONFLICT(id) DO UPDATE SET
    summary = COALESCE(@summary, summary),
    first_prompt = COALESCE(@first_prompt, first_prompt),
    message_count = MAX(COALESCE(@message_count, 0), COALESCE(message_count, 0)),
    git_branch = COALESCE(@git_branch, git_branch),
    model = COALESCE(@model, model),
    project_path = COALESCE(@project_path, project_path),
    created_at = COALESCE(created_at, @created_at),
    modified_at = COALESCE(@modified_at, modified_at),
    file_path = COALESCE(@file_path, file_path),
    file_mtime = COALESCE(@file_mtime, file_mtime),
    parent_session_id = COALESCE(@parent_session_id, parent_session_id),
    is_subagent = CASE
      WHEN COALESCE(@codex_lineage_checked, 0) = 1 THEN COALESCE(@is_subagent, 0)
      ELSE is_subagent
    END,
    codex_lineage_checked = MAX(COALESCE(codex_lineage_checked, 0), COALESCE(@codex_lineage_checked, 0)),
    indexed_at = CASE
      WHEN COALESCE(@file_path, '') <> COALESCE(file_path, '')
        OR COALESCE(@file_mtime, -1) <> COALESCE(file_mtime, -1)
        OR COALESCE(@modified_at, '') <> COALESCE(modified_at, '')
        OR COALESCE(@message_count, 0) <> COALESCE(message_count, 0)
      THEN NULL
      ELSE indexed_at
    END
`;

function isLowSignalPrompt(text: string | null | undefined): boolean {
  if (!text) return true;
  const t = text.trim();
  if (!t) return true;
  if (LOW_SIGNAL_PROMPT_RE.test(t)) return true;
  if (t.startsWith(CAVEAT_PREFIX)) return true;
  return false;
}

function extractClaudeTextFromContent(content: unknown): string | null {
  if (typeof content === 'string') return sanitizeConversationText(content);
  if (Array.isArray(content)) {
    const joined = content
      .filter((b: any) => b?.type === 'text' && typeof b?.text === 'string')
      .map((b: any) => b.text)
      .join('\n');
    return sanitizeConversationText(joined);
  }
  return null;
}

function extractCodexTextFromContent(content: unknown): string | null {
  if (!Array.isArray(content)) return null;
  const joined = content
    .filter((b: any) => (b?.type === 'input_text' || b?.type === 'output_text') && typeof b?.text === 'string')
    .map((b: any) => b.text)
    .join('\n');
  return sanitizeConversationText(joined);
}

function extractCopilotMessageText(message: any): string | null {
  if (!message) return null;
  if (typeof message.text === 'string') return sanitizeConversationText(message.text);
  if (Array.isArray(message.parts)) {
    const joined = message.parts
      .map((part: any) => typeof part?.text === 'string' ? part.text : '')
      .filter(Boolean)
      .join('\n');
    return sanitizeConversationText(joined);
  }
  return null;
}

function extractCopilotResponseText(response: any): string | null {
  if (!Array.isArray(response)) return null;
  const joined = response
    .map((item: any) => typeof item?.value === 'string' ? item.value : '')
    .filter(Boolean)
    .join('\n\n');
  return sanitizeConversationText(joined);
}

function cleanCodexPrompt(text: string | null | undefined): string | null {
  if (!text) return null;
  const cleaned = text
    .replace(/<environment_context>[\s\S]*?<\/environment_context>/gi, '')
    .replace(/^# Context from my IDE setup:[\s\S]*?## My request for Codex:\s*/i, '')
    .replace(/^# Context from my IDE setup:[\s\S]*?## My request:\s*/i, '')
    .trim();
  return sanitizeConversationText(cleaned);
}

function slugifyProjectPath(projectPath: string | null | undefined, fallback: string): string {
  if (!projectPath) return fallback;
  const slug = projectPath
    .replace(/[:\\/]/g, '-')
    .replace(/\s+/g, '-')
    .replace(/^-+|-+$/g, '');
  return slug || fallback;
}

function createSessionUpsertStatement() {
  return getDb().prepare(SESSION_UPSERT_SQL);
}

function yieldToEventLoop(): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, 0));
}

export async function scanAllProjects(): Promise<number> {
  const upsert = createSessionUpsertStatement();

  let count = 0;
  count += await scanClaudeProjects(upsert);
  await yieldToEventLoop();
  count += await scanCodexSessions(upsert);
  await yieldToEventLoop();
  count += await scanVsCodeCopilotSessions(upsert);
  await yieldToEventLoop();
  count += await scanCursorCopilotSessions(upsert);
  return count;
}

export async function upsertSessionFromFile(filePath: string): Promise<string | null> {
  const normalized = filePath.replace(/[\\/]+/g, '/').toLowerCase();
  const upsert = createSessionUpsertStatement();
  const parentDir = path.dirname(filePath);

  if (
    path.basename(filePath) === 'state.vscdb'
    && normalized.includes('/appdata/roaming/cursor/user/workspacestorage/')
  ) {
    return upsertCursorWorkspaceStateSessionFile(upsert, filePath);
  }

  if (normalized.includes('/chatSessions/'.toLowerCase()) && path.extname(filePath).toLowerCase() === '.json') {
    return upsertVsCodeCopilotSessionFile(upsert, filePath);
  }

  if (normalized.includes('/.cursor/projects/') && normalized.includes('/agent-transcripts/')) {
    return upsertCursorTranscriptSessionFile(upsert, filePath);
  }

  if (
    normalized.includes('/.codex/sessions/')
    && path.extname(filePath).toLowerCase() === '.jsonl'
    && path.basename(filePath).startsWith('rollout-')
  ) {
    return upsertCodexSessionFile(upsert, filePath);
  }

  if (
    normalized.includes('/.claude/projects/')
    && path.extname(filePath).toLowerCase() === '.jsonl'
    && path.resolve(path.dirname(parentDir)) === path.resolve(PROJECTS_DIR)
  ) {
    return upsertClaudeSessionFile(upsert, filePath);
  }

  return null;
}

async function upsertClaudeSessionFile(upsert: any, filePath: string): Promise<string | null> {
  if (!fs.existsSync(filePath)) return null;

  const slug = path.basename(path.dirname(filePath));
  const sessionId = path.basename(filePath, '.jsonl');
  const stat = fs.statSync(filePath);
  const meta = await parseClaudeFirstLines(filePath);

  upsert.run({
    id: sessionId,
    project_slug: slug,
    project_path: null,
    summary: null,
    first_prompt: sanitizeConversationText(meta.firstPrompt)?.slice(0, 500) || null,
    message_count: 0,
    git_branch: meta.gitBranch || null,
    model: meta.model || null,
    created_at: meta.timestamp || null,
    modified_at: new Date(stat.mtimeMs).toISOString(),
    file_path: filePath,
    file_mtime: stat.mtimeMs,
    parent_session_id: null,
    is_subagent: 0,
    codex_lineage_checked: 0,
  });

  return sessionId;
}

async function upsertCodexSessionFile(upsert: any, filePath: string): Promise<string | null> {
  if (!fs.existsSync(filePath)) return null;

  const meta = await parseCodexFirstLines(filePath);
  if (!meta.sessionId) return null;

  const stat = fs.statSync(filePath);
  const indexEntry = readCodexSessionIndex().get(meta.sessionId);
  const summary = sanitizeConversationText(indexEntry?.thread_name || null);
  const projectPath = meta.cwd || null;
  const sessionId = `${CODEX_ID_PREFIX}${meta.sessionId}`;

  upsert.run({
    id: sessionId,
    project_slug: slugifyProjectPath(projectPath, 'codex-unknown'),
    project_path: projectPath,
    summary,
    first_prompt: (!isLowSignalPrompt(meta.firstPrompt) ? meta.firstPrompt : null)?.slice(0, 500) || null,
    message_count: 0,
    git_branch: null,
    model: meta.model || null,
    created_at: meta.timestamp || null,
    modified_at: indexEntry?.updated_at || new Date(stat.mtimeMs).toISOString(),
    file_path: filePath,
    file_mtime: stat.mtimeMs,
    parent_session_id: meta.parentSessionId || null,
    is_subagent: meta.isSubagent ? 1 : 0,
    codex_lineage_checked: 1,
  });

  return sessionId;
}

async function upsertVsCodeCopilotSessionFile(upsert: any, filePath: string): Promise<string | null> {
  if (!fs.existsSync(filePath)) return null;

  const workspacePath = readCopilotWorkspacePath(path.join(path.dirname(path.dirname(filePath)), 'workspace.json'));
  const stat = fs.statSync(filePath);
  const meta = parseCopilotSessionMeta(filePath, workspacePath);
  if (!meta.sessionId) return null;

  const sessionId = `${COPILOT_ID_PREFIX}code-${meta.sessionId}`;
  upsert.run({
    id: sessionId,
    project_slug: slugifyProjectPath(meta.projectPath, 'copilot-code-unknown'),
    project_path: meta.projectPath,
    summary: null,
    first_prompt: meta.firstPrompt?.slice(0, 500) || null,
    message_count: meta.messageCount,
    git_branch: null,
    model: meta.model,
    created_at: meta.createdAt || new Date(stat.mtimeMs).toISOString(),
    modified_at: meta.modifiedAt || new Date(stat.mtimeMs).toISOString(),
    file_path: filePath,
    file_mtime: stat.mtimeMs,
    parent_session_id: null,
    is_subagent: 0,
    codex_lineage_checked: 0,
  });

  return sessionId;
}

async function upsertCursorTranscriptSessionFile(upsert: any, filePath: string): Promise<string | null> {
  if (!fs.existsSync(filePath)) return null;

  const db = getDb();
  const composerId = path.basename(filePath, '.jsonl');
  const metadata = buildCursorComposerMetadataIndex().get(composerId) || null;
  const conversation = readCursorComposerConversation(composerId);
  const transcriptMeta = await parseCursorTranscriptMeta(filePath);
  const stat = fs.statSync(filePath);
  const sessionId = `${COPILOT_ID_PREFIX}cursor-${composerId}`;
  const summary = metadata?.name || metadata?.subtitle || null;
  const firstPrompt = conversation.bubbles
    .find(bubble => bubble.role === 'user' && bubble.text && !isLowSignalPrompt(bubble.text))
    ?.text || transcriptMeta.firstPrompt;
  const createdAt = conversation.bubbles[0]?.createdAt
    || (metadata?.createdAt ? new Date(metadata.createdAt).toISOString() : transcriptMeta.createdAt);
  const modifiedAt = conversation.bubbles[conversation.bubbles.length - 1]?.createdAt
    || (metadata?.lastUpdatedAt ? new Date(metadata.lastUpdatedAt).toISOString() : transcriptMeta.modifiedAt);
  const messageCount = conversation.bubbles.length > 0
    ? conversation.bubbles.reduce((sum, bubble) => sum + countCursorBubbleMessages(bubble), 0)
    : transcriptMeta.messageCount;
  const projectDirName = path.basename(path.dirname(path.dirname(filePath)));

  if (metadata?.workspaceId) {
    db.prepare('DELETE FROM sessions WHERE id = ?').run(`${COPILOT_ID_PREFIX}cursor-${metadata.workspaceId}`);
    db.prepare('DELETE FROM sessions WHERE id = ?').run(`${COPILOT_ID_PREFIX}cursor-${metadata.workspaceId}-${composerId}`);
  }

  upsert.run({
    id: sessionId,
    project_slug: slugifyProjectPath(metadata?.workspacePath || projectDirName, 'copilot-cursor-unknown'),
    project_path: metadata?.workspacePath || null,
    summary: summary && summary !== firstPrompt ? summary.slice(0, 500) : null,
    first_prompt: firstPrompt?.slice(0, 500) || null,
    message_count: messageCount,
    git_branch: metadata?.activeBranch || metadata?.cachedGitBranch || metadata?.createdOnBranch || null,
    model: null,
    created_at: createdAt || new Date(stat.mtimeMs).toISOString(),
    modified_at: modifiedAt || new Date(stat.mtimeMs).toISOString(),
    file_path: filePath,
    file_mtime: stat.mtimeMs,
    parent_session_id: null,
    is_subagent: 0,
    codex_lineage_checked: 0,
  });

  return sessionId;
}

async function upsertCursorWorkspaceStateSessionFile(upsert: any, stateDbPath: string): Promise<string | null> {
  if (!fs.existsSync(stateDbPath)) return null;

  const db = getDb();
  const stat = fs.statSync(stateDbPath);
  const state = readCursorWorkspaceState(stateDbPath);
  if (!state) return null;

  const sessionId = `${COPILOT_ID_PREFIX}cursor-${state.workspaceId}`;
  const promptTexts = state.prompts
    .map(prompt => sanitizeConversationText(prompt.text))
    .filter((value): value is string => Boolean(value));
  const composerSummary = state.composers
    .slice()
    .sort((a, b) => (b.lastUpdatedAt || b.createdAt || 0) - (a.lastUpdatedAt || a.createdAt || 0))
    .map(composer => sanitizeConversationText(composer.name || composer.subtitle || null))
    .find((value): value is string => Boolean(value)) || null;
  const firstPrompt = promptTexts.find(text => !isLowSignalPrompt(text)) || null;
  const generationTimes = state.generations
    .map(entry => typeof entry.unixMs === 'number' ? new Date(entry.unixMs).toISOString() : null)
    .filter((value): value is string => Boolean(value));

  if (promptTexts.length === 0 && generationTimes.length === 0 && !composerSummary) return null;

  const duplicateComposer = state.workspacePath
    ? db.prepare(`
      SELECT id FROM sessions
      WHERE id <> ?
        AND id LIKE 'copilot-cursor-%'
        AND project_path = ?
        AND file_path <> ?
      LIMIT 1
    `).get(sessionId, state.workspacePath, stateDbPath) as { id: string } | undefined
    : undefined;

  if (duplicateComposer) {
    db.prepare('DELETE FROM sessions WHERE id = ?').run(sessionId);
    return null;
  }

  upsert.run({
    id: sessionId,
    project_slug: slugifyProjectPath(state.workspacePath, 'copilot-cursor-unknown'),
    project_path: state.workspacePath,
    summary: composerSummary && composerSummary !== firstPrompt ? composerSummary.slice(0, 500) : null,
    first_prompt: firstPrompt?.slice(0, 500) || null,
    message_count: state.prompts.length + state.generations.length,
    git_branch: state.cachedGitBranch,
    model: null,
    created_at: generationTimes[0] || new Date(stat.mtimeMs).toISOString(),
    modified_at: generationTimes[generationTimes.length - 1] || new Date(stat.mtimeMs).toISOString(),
    file_path: stateDbPath,
    file_mtime: stat.mtimeMs,
    parent_session_id: null,
    is_subagent: 0,
    codex_lineage_checked: 0,
  });

  return sessionId;
}

async function scanClaudeProjects(upsert: any): Promise<number> {
  const db = getDb();
  let count = 0;

  if (!fs.existsSync(PROJECTS_DIR)) return 0;

  const projectDirs = fs.readdirSync(PROJECTS_DIR, { withFileTypes: true })
    .filter(d => d.isDirectory())
    .map(d => d.name);

  for (const slug of projectDirs) {
    const projectDir = path.join(PROJECTS_DIR, slug);
    const indexPath = path.join(projectDir, 'sessions-index.json');

    if (fs.existsSync(indexPath)) {
      try {
        const indexData = JSON.parse(fs.readFileSync(indexPath, 'utf-8'));
        const entries: any[] = indexData.entries || [];
        for (const entry of entries) {
          if (entry.isSidechain) continue;
          const filePath = entry.fullPath || path.join(projectDir, `${entry.sessionId}.jsonl`);
          let summary = sanitizeConversationText(entry.summary);
          let firstPrompt = sanitizeConversationText(entry.firstPrompt);
          if (!summary && isLowSignalPrompt(firstPrompt)) {
            const meta = await parseClaudeFirstLines(filePath);
            if (!isLowSignalPrompt(meta.firstPrompt)) {
              firstPrompt = meta.firstPrompt!;
            }
          }
          upsert.run({
            id: entry.sessionId,
            project_slug: slug,
            project_path: entry.projectPath || null,
            summary,
            first_prompt: (!isLowSignalPrompt(firstPrompt) ? firstPrompt : null)?.slice(0, 500) || null,
            message_count: entry.messageCount || 0,
            git_branch: entry.gitBranch || null,
            model: null,
            created_at: entry.created || null,
            modified_at: entry.modified || entry.lastModified || null,
            file_path: filePath,
            file_mtime: entry.fileMtime || null,
            parent_session_id: null,
            is_subagent: 0,
            codex_lineage_checked: 0,
          });
          count++;
        }
      } catch (e) {
        console.error(`Failed to parse index for ${slug}:`, e);
      }
    }

    const jsonlFiles = fs.readdirSync(projectDir).filter(f => f.endsWith('.jsonl'));
    for (const file of jsonlFiles) {
      const sessionId = path.basename(file, '.jsonl');
      const existing = db.prepare('SELECT file_mtime FROM sessions WHERE id = ?').get(sessionId) as any;
      const filePath = path.join(projectDir, file);
      const stat = fs.statSync(filePath);
      if (existing && existing.file_mtime >= stat.mtimeMs) continue;
      if (existing) continue;

      try {
        const meta = await parseClaudeFirstLines(filePath);
        upsert.run({
          id: sessionId,
          project_slug: slug,
          project_path: null,
          summary: null,
          first_prompt: sanitizeConversationText(meta.firstPrompt)?.slice(0, 500) || null,
          message_count: 0,
          git_branch: meta.gitBranch || null,
          model: meta.model || null,
          created_at: meta.timestamp || null,
          modified_at: new Date(stat.mtimeMs).toISOString(),
          file_path: filePath,
          file_mtime: stat.mtimeMs,
          parent_session_id: null,
          is_subagent: 0,
          codex_lineage_checked: 0,
        });
        count++;
      } catch (e) {
        console.warn('[scanner] Skip file', filePath, ':', (e as Error).message);
      }
    }
  }

  return count;
}

async function scanCodexSessions(upsert: any): Promise<number> {
  const db = getDb();
  let count = 0;

  if (!fs.existsSync(CODEX_SESSIONS_DIR)) return 0;

  const indexMap = readCodexSessionIndex();
  const files = listFiles(CODEX_SESSIONS_DIR, filePath => filePath.endsWith('.jsonl'));

  for (const filePath of files) {
    try {
      const meta = await parseCodexFirstLines(filePath);
      if (!meta.sessionId) continue;

      const sessionId = `${CODEX_ID_PREFIX}${meta.sessionId}`;
      const stat = fs.statSync(filePath);
      const existing = db.prepare('SELECT file_mtime, codex_lineage_checked FROM sessions WHERE id = ?').get(sessionId) as any;
      if (existing && existing.file_mtime >= stat.mtimeMs && existing.codex_lineage_checked === 1) continue;

      const indexEntry = indexMap.get(meta.sessionId);
      const summary = sanitizeConversationText(indexEntry?.thread_name || null);
      const projectPath = meta.cwd || null;

      upsert.run({
        id: sessionId,
        project_slug: slugifyProjectPath(projectPath, 'codex-unknown'),
        project_path: projectPath,
        summary,
        first_prompt: (!isLowSignalPrompt(meta.firstPrompt) ? meta.firstPrompt : null)?.slice(0, 500) || null,
        message_count: 0,
        git_branch: null,
        model: meta.model || null,
        created_at: meta.timestamp || null,
        modified_at: indexEntry?.updated_at || new Date(stat.mtimeMs).toISOString(),
        file_path: filePath,
        file_mtime: stat.mtimeMs,
        parent_session_id: meta.parentSessionId || null,
        is_subagent: meta.isSubagent ? 1 : 0,
        codex_lineage_checked: 1,
      });
      count++;
    } catch (e) {
      console.warn('[scanner] Skip Codex session', filePath, ':', (e as Error).message);
    }
  }

  return count;
}

async function scanVsCodeCopilotSessions(upsert: any): Promise<number> {
  const db = getDb();
  let count = 0;

  if (!fs.existsSync(VSCODE_COPILOT_WORKSPACE_STORAGE_DIR)) return 0;

  const workspaceDirs = fs.readdirSync(VSCODE_COPILOT_WORKSPACE_STORAGE_DIR, { withFileTypes: true })
    .filter(entry => entry.isDirectory())
    .map(entry => path.join(VSCODE_COPILOT_WORKSPACE_STORAGE_DIR, entry.name));

  for (const workspaceDir of workspaceDirs) {
    const chatSessionsDir = path.join(workspaceDir, 'chatSessions');
    if (!fs.existsSync(chatSessionsDir)) continue;

    const workspacePath = readCopilotWorkspacePath(path.join(workspaceDir, 'workspace.json'));
    const files = fs.readdirSync(chatSessionsDir)
      .filter(name => name.endsWith('.json'))
      .map(name => path.join(chatSessionsDir, name));

    for (const filePath of files) {
      try {
        const stat = fs.statSync(filePath);
        const meta = parseCopilotSessionMeta(filePath, workspacePath);
        if (!meta.sessionId) continue;

        const sessionId = `${COPILOT_ID_PREFIX}code-${meta.sessionId}`;
        const existing = db.prepare('SELECT file_mtime FROM sessions WHERE id = ?').get(sessionId) as any;
        if (existing && existing.file_mtime >= stat.mtimeMs) continue;

        upsert.run({
          id: sessionId,
          project_slug: slugifyProjectPath(meta.projectPath, 'copilot-code-unknown'),
          project_path: meta.projectPath,
          summary: null,
          first_prompt: meta.firstPrompt?.slice(0, 500) || null,
          message_count: meta.messageCount,
          git_branch: null,
          model: meta.model,
          created_at: meta.createdAt || new Date(stat.mtimeMs).toISOString(),
          modified_at: meta.modifiedAt || new Date(stat.mtimeMs).toISOString(),
          file_path: filePath,
          file_mtime: stat.mtimeMs,
          parent_session_id: null,
          is_subagent: 0,
          codex_lineage_checked: 0,
        });
        count++;
      } catch (e) {
        console.warn('[scanner] Skip Copilot session', filePath, ':', (e as Error).message);
      }
    }
  }

  return count;
}

async function scanCursorCopilotSessions(upsert: any): Promise<number> {
  const globalResult = await scanCursorGlobalComposerSessions(upsert);
  const transcriptResult = await scanCursorTranscriptSessions(upsert, globalResult.composerIdsWithBubbles);
  const skipWorkspaceIds = new Set<string>([
    ...globalResult.workspaceIdsWithComposerSessions,
    ...transcriptResult.workspaceIdsWithTranscripts,
  ]);
  return globalResult.count + transcriptResult.count + await scanCursorWorkspaceStateSessions(upsert, skipWorkspaceIds);
}

async function scanCursorGlobalComposerSessions(upsert: any): Promise<{
  count: number;
  composerIdsWithBubbles: Set<string>;
  workspaceIdsWithComposerSessions: Set<string>;
}> {
  const composerMetadataIndex = buildCursorComposerMetadataIndex();
  const composerIds = listCursorComposerIdsWithBubbles();
  const countSet = new Set<string>();
  const workspaceIdsWithComposerSessions = new Set<string>();
  let count = 0;

  for (const composerId of composerIds) {
    const metadata = composerMetadataIndex.get(composerId) || null;
    const conversation = readCursorComposerConversation(composerId);
    if (conversation.bubbles.length === 0) continue;

    const firstPrompt = conversation.bubbles
      .find(bubble => bubble.role === 'user' && bubble.text && !isLowSignalPrompt(bubble.text))
      ?.text || null;
    const summary = metadata?.name || metadata?.subtitle || null;
    const createdAt = conversation.bubbles[0]?.createdAt || null;
    const modifiedAt = conversation.bubbles[conversation.bubbles.length - 1]?.createdAt || null;
    const messageCount = conversation.bubbles.reduce((sum, bubble) => sum + countCursorBubbleMessages(bubble), 0);
    const sessionId = `${COPILOT_ID_PREFIX}cursor-${composerId}`;

    if (metadata?.workspaceId) {
      workspaceIdsWithComposerSessions.add(metadata.workspaceId);
      getDb().prepare('DELETE FROM sessions WHERE id = ?').run(`${COPILOT_ID_PREFIX}cursor-${metadata.workspaceId}`);
      getDb().prepare('DELETE FROM sessions WHERE id = ?').run(`${COPILOT_ID_PREFIX}cursor-${metadata.workspaceId}-${composerId}`);
    }

    upsert.run({
      id: sessionId,
      project_slug: slugifyProjectPath(metadata?.workspacePath || composerId, 'copilot-cursor-unknown'),
      project_path: metadata?.workspacePath || null,
      summary: summary && summary !== firstPrompt ? summary.slice(0, 500) : null,
      first_prompt: firstPrompt?.slice(0, 500) || null,
      message_count: messageCount,
      git_branch: metadata?.activeBranch || metadata?.cachedGitBranch || metadata?.createdOnBranch || null,
      model: null,
      created_at: createdAt,
      modified_at: modifiedAt,
      file_path: buildCursorComposerVirtualPath(composerId),
      file_mtime: null,
      parent_session_id: null,
      is_subagent: 0,
      codex_lineage_checked: 0,
    });
    countSet.add(composerId);
    count++;
  }

  return {
    count,
    composerIdsWithBubbles: countSet,
    workspaceIdsWithComposerSessions,
  };
}

async function scanCursorTranscriptSessions(
  upsert: any,
  skipComposerIds: Set<string> = new Set<string>(),
): Promise<{
  count: number;
  workspaceIdsWithTranscripts: Set<string>;
}> {
  const db = getDb();
  let count = 0;
  const workspaceIdsWithTranscripts = new Set<string>();

  if (!fs.existsSync(CURSOR_PROJECTS_DIR)) {
    return { count, workspaceIdsWithTranscripts };
  }

  const composerMetadataIndex = buildCursorComposerMetadataIndex();
  const transcriptFiles = listFiles(CURSOR_PROJECTS_DIR, filePath => {
    return filePath.endsWith('.jsonl') && filePath.includes(`${path.sep}agent-transcripts${path.sep}`);
  });

  for (const filePath of transcriptFiles) {
    try {
      const stat = fs.statSync(filePath);
      const composerId = path.basename(filePath, '.jsonl');
      if (skipComposerIds.has(composerId)) continue;
      const metadata = composerMetadataIndex.get(composerId) || null;
      const sessionId = `${COPILOT_ID_PREFIX}cursor-${composerId}`;

      const transcriptMeta = await parseCursorTranscriptMeta(filePath);
      const conversation = readCursorComposerConversation(composerId);
      const summary = metadata?.name || metadata?.subtitle || null;
      const firstPrompt = conversation.bubbles
        .find(bubble => bubble.role === 'user' && bubble.text && !isLowSignalPrompt(bubble.text))
        ?.text || transcriptMeta.firstPrompt;
      const createdAt = conversation.bubbles[0]?.createdAt
        || (metadata?.createdAt ? new Date(metadata.createdAt).toISOString() : transcriptMeta.createdAt);
      const modifiedAt = conversation.bubbles[conversation.bubbles.length - 1]?.createdAt
        || (metadata?.lastUpdatedAt ? new Date(metadata.lastUpdatedAt).toISOString() : transcriptMeta.modifiedAt);
      const messageCount = conversation.bubbles.length > 0
        ? conversation.bubbles.reduce((sum, bubble) => sum + countCursorBubbleMessages(bubble), 0)
        : transcriptMeta.messageCount;
      const projectDirName = path.basename(path.dirname(path.dirname(filePath)));

      if (metadata?.workspaceId) {
        workspaceIdsWithTranscripts.add(metadata.workspaceId);
        db.prepare('DELETE FROM sessions WHERE id = ?').run(`${COPILOT_ID_PREFIX}cursor-${metadata.workspaceId}`);
        db.prepare('DELETE FROM sessions WHERE id = ?').run(`${COPILOT_ID_PREFIX}cursor-${metadata.workspaceId}-${composerId}`);
      }

      upsert.run({
        id: sessionId,
        project_slug: slugifyProjectPath(metadata?.workspacePath || projectDirName, 'copilot-cursor-unknown'),
        project_path: metadata?.workspacePath || null,
        summary: summary && summary !== firstPrompt ? summary.slice(0, 500) : null,
        first_prompt: firstPrompt?.slice(0, 500) || null,
        message_count: messageCount,
        git_branch: metadata?.activeBranch || metadata?.cachedGitBranch || metadata?.createdOnBranch || null,
        model: null,
        created_at: createdAt || new Date(stat.mtimeMs).toISOString(),
        modified_at: modifiedAt || new Date(stat.mtimeMs).toISOString(),
        file_path: filePath,
        file_mtime: stat.mtimeMs,
        parent_session_id: null,
        is_subagent: 0,
        codex_lineage_checked: 0,
      });
      count++;
    } catch (e) {
      console.warn('[scanner] Skip Cursor transcript', filePath, ':', (e as Error).message);
    }
  }

  return { count, workspaceIdsWithTranscripts };
}

function countCursorBubbleMessages(
  bubble: { thinking: string | null; text: string | null; references: { path: string }[]; toolName: string | null; toolResult: string | null }
): number {
  const hasMainContent = Boolean(
    bubble.text
      || bubble.references.length > 0
      || bubble.toolName
      || bubble.toolResult
  );

  return (bubble.thinking ? 1 : 0) + (hasMainContent ? 1 : 0);
}

async function scanCursorWorkspaceStateSessions(upsert: any, skipWorkspaceIds: Set<string>): Promise<number> {
  const db = getDb();
  let count = 0;

  if (!fs.existsSync(CURSOR_COPILOT_WORKSPACE_STORAGE_DIR)) return 0;

  const workspaceDirs = fs.readdirSync(CURSOR_COPILOT_WORKSPACE_STORAGE_DIR, { withFileTypes: true })
    .filter(entry => entry.isDirectory())
    .map(entry => path.join(CURSOR_COPILOT_WORKSPACE_STORAGE_DIR, entry.name));

  for (const workspaceDir of workspaceDirs) {
    const stateDbPath = path.join(workspaceDir, 'state.vscdb');
    if (!fs.existsSync(stateDbPath)) continue;

    try {
      const stat = fs.statSync(stateDbPath);
      const state = readCursorWorkspaceState(stateDbPath);
      if (!state || skipWorkspaceIds.has(state.workspaceId)) continue;

      const sessionId = `${COPILOT_ID_PREFIX}cursor-${state.workspaceId}`;
      const promptTexts = state.prompts
        .map(prompt => sanitizeConversationText(prompt.text))
        .filter((value): value is string => Boolean(value));
      const composerSummary = state.composers
        .slice()
        .sort((a, b) => (b.lastUpdatedAt || b.createdAt || 0) - (a.lastUpdatedAt || a.createdAt || 0))
        .map(composer => sanitizeConversationText(composer.name || composer.subtitle || null))
        .find((value): value is string => Boolean(value)) || null;
      const firstPrompt = promptTexts.find(text => !isLowSignalPrompt(text)) || null;
      const generationTimes = state.generations
        .map(entry => typeof entry.unixMs === 'number' ? new Date(entry.unixMs).toISOString() : null)
        .filter((value): value is string => Boolean(value));

      if (promptTexts.length === 0 && generationTimes.length === 0 && !composerSummary) continue;

      upsert.run({
        id: sessionId,
        project_slug: slugifyProjectPath(state.workspacePath, 'copilot-cursor-unknown'),
        project_path: state.workspacePath,
        summary: composerSummary && composerSummary !== firstPrompt ? composerSummary.slice(0, 500) : null,
        first_prompt: firstPrompt?.slice(0, 500) || null,
        message_count: state.prompts.length + state.generations.length,
        git_branch: state.cachedGitBranch,
        model: null,
        created_at: generationTimes[0] || new Date(stat.mtimeMs).toISOString(),
        modified_at: generationTimes[generationTimes.length - 1] || new Date(stat.mtimeMs).toISOString(),
        file_path: stateDbPath,
        file_mtime: stat.mtimeMs,
        parent_session_id: null,
        is_subagent: 0,
        codex_lineage_checked: 0,
      });
      count++;
    } catch (e) {
      console.warn('[scanner] Skip Cursor Copilot session', stateDbPath, ':', (e as Error).message);
    }
  }

  return count;
}

async function parseCursorTranscriptMeta(filePath: string): Promise<{
  firstPrompt: string | null;
  createdAt: string | null;
  modifiedAt: string | null;
  messageCount: number;
}> {
  return new Promise((resolve) => {
    const result = {
      firstPrompt: null as string | null,
      createdAt: null as string | null,
      modifiedAt: null as string | null,
      messageCount: 0,
    };

    const stream = fs.createReadStream(filePath, { encoding: 'utf-8' });
    const rl = readline.createInterface({ input: stream });

    rl.on('line', (line) => {
      if (!line.trim()) return;
      try {
        const obj = JSON.parse(line);
        const content = Array.isArray(obj?.message?.content) ? obj.message.content : [];
        const text = sanitizeConversationText(
          content
            .filter((block: any) => block?.type === 'text' && typeof block?.text === 'string')
            .map((block: any) => unwrapCursorTranscriptUserText(block.text))
            .join('\n\n')
        );

        if (!text) return;
        result.messageCount += 1;
        if (obj?.role === 'user' && !result.firstPrompt && !isLowSignalPrompt(text)) {
          result.firstPrompt = text;
        }
      } catch {
        // ignore malformed transcript lines
      }
    });

    rl.on('close', () => resolve(result));
    rl.on('error', () => resolve(result));
  });
}

function listFiles(root: string, predicate: (filePath: string) => boolean): string[] {
  const results: string[] = [];
  const stack = [root];

  while (stack.length > 0) {
    const current = stack.pop()!;
    const entries = fs.readdirSync(current, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = path.join(current, entry.name);
      if (entry.isDirectory()) {
        stack.push(fullPath);
      } else if (entry.isFile() && predicate(fullPath)) {
        results.push(fullPath);
      }
    }
  }

  return results;
}

function readCodexSessionIndex(): Map<string, CodexSessionIndexEntry> {
  const indexMap = new Map<string, CodexSessionIndexEntry>();
  if (!fs.existsSync(CODEX_SESSION_INDEX_PATH)) return indexMap;

  const lines = fs.readFileSync(CODEX_SESSION_INDEX_PATH, 'utf-8').split(/\r?\n/).filter(Boolean);
  for (const line of lines) {
    try {
      const entry = JSON.parse(line) as CodexSessionIndexEntry;
      if (typeof entry.id === 'string' && entry.id.trim()) {
        indexMap.set(entry.id, entry);
      }
    } catch {
      // ignore malformed index lines
    }
  }

  return indexMap;
}

function readCopilotWorkspacePath(workspaceJsonPath: string): string | null {
  if (!fs.existsSync(workspaceJsonPath)) return null;

  try {
    const workspace = JSON.parse(fs.readFileSync(workspaceJsonPath, 'utf-8')) as Record<string, unknown>;
    const candidate = typeof workspace.folder === 'string'
      ? workspace.folder
      : typeof workspace.workspace === 'string'
        ? workspace.workspace
        : null;
    return normalizeFileUriToPath(candidate);
  } catch {
    return null;
  }
}

function parseCopilotSessionMeta(filePath: string, workspacePath: string | null): {
  sessionId: string | null;
  firstPrompt: string | null;
  projectPath: string | null;
  createdAt: string | null;
  modifiedAt: string | null;
  messageCount: number;
  model: string | null;
} {
  const raw = JSON.parse(fs.readFileSync(filePath, 'utf-8')) as Record<string, any>;
  const requests = Array.isArray(raw.requests) ? raw.requests : [];
  const timestamps = requests
    .map((request: any) => normalizeTimestamp(request.timestamp))
    .filter((value: string | null): value is string => Boolean(value));
  const firstPrompt = sanitizeConversationText(
    requests
      .map((request: any) => extractCopilotMessageText(request.message))
      .find((text: string | null | undefined) => !isLowSignalPrompt(text)) || null
  );
  const projectPathFromResponse = requests
    .map((request: any) => extractCopilotProjectPathFromRequest(request))
    .find((value: string | null): value is string => Boolean(value)) || null;

  return {
    sessionId: typeof raw.sessionId === 'string' ? raw.sessionId : path.basename(filePath, path.extname(filePath)),
    firstPrompt,
    projectPath: workspacePath || projectPathFromResponse,
    createdAt: timestamps[0] || null,
    modifiedAt: timestamps[timestamps.length - 1] || null,
    messageCount: requests.reduce(
      (sum: number, request: any) =>
        sum + (extractCopilotMessageText(request.message) ? 1 : 0) + (extractCopilotResponseText(request.response) ? 1 : 0),
      0,
    ),
    model: null,
  };
}

function extractCopilotProjectPathFromRequest(request: any): string | null {
  const baseUriCandidate = Array.isArray(request?.response)
    ? request.response
      .map((item: any) => getCopilotBaseUriPath(item?.baseUri))
      .find((value: string | null): value is string => Boolean(value))
    : null;

  if (baseUriCandidate) return baseUriCandidate;

  if (Array.isArray(request?.variableData?.variables)) {
    for (const variable of request.variableData.variables) {
      const fsPath = variable?.value?.fsPath;
      if (typeof fsPath === 'string' && fsPath.trim()) {
        return path.dirname(fsPath);
      }
    }
  }

  return null;
}

function getCopilotBaseUriPath(baseUri: any): string | null {
  if (!baseUri) return null;
  if (typeof baseUri.fsPath === 'string' && baseUri.fsPath.trim()) {
    return baseUri.fsPath;
  }
  if (typeof baseUri.scheme === 'string' && typeof baseUri.path === 'string' && baseUri.scheme === 'file') {
    return normalizeFileUriToPath(`file://${baseUri.path}`);
  }
  if (typeof baseUri.path === 'string' && baseUri.path.trim()) {
    return normalizeFileUriToPath(baseUri.path);
  }
  return null;
}

function normalizeTimestamp(value: unknown): string | null {
  if (typeof value === 'number' && Number.isFinite(value)) {
    return new Date(value).toISOString();
  }
  if (typeof value === 'string' && value.trim()) {
    const date = new Date(value);
    return Number.isNaN(date.getTime()) ? null : date.toISOString();
  }
  return null;
}

function normalizeFileUriToPath(value: string | null): string | null {
  if (!value) return null;

  try {
    if (value.startsWith('file://')) {
      return fileURLToPath(value);
    }
  } catch {
    // fall through
  }

  if (/^\/[A-Za-z]:\//.test(value)) {
    return value.slice(1).replace(/\//g, path.sep);
  }

  return value.replace(/\//g, path.sep);
}

function unwrapCursorTranscriptUserText(text: string): string {
  const match = text.match(/^<user_query>\s*([\s\S]*?)\s*<\/user_query>$/i);
  return match?.[1]?.trim() || text;
}

async function parseClaudeFirstLines(filePath: string): Promise<{
  firstPrompt?: string; gitBranch?: string; model?: string; timestamp?: string;
}> {
  return new Promise((resolve) => {
    const result: any = {};
    let assistantCandidate: string | null = null;
    const stream = fs.createReadStream(filePath, { encoding: 'utf-8' });
    const rl = readline.createInterface({ input: stream });
    let lineCount = 0;

    rl.on('line', (line) => {
      lineCount++;
      if (lineCount > 200) { rl.close(); return; }
      try {
        const obj = JSON.parse(line);
        if ((obj.type === 'user' || obj.type === 'assistant') && !result.firstPrompt) {
          const text = extractClaudeTextFromContent(obj.message?.content);
          if (!isLowSignalPrompt(text)) {
            if (obj.type === 'user') {
              result.firstPrompt = text;
            } else if (!assistantCandidate) {
              assistantCandidate = text!;
            }
          }
          if (!result.timestamp) result.timestamp = obj.timestamp;
          if (!result.gitBranch) result.gitBranch = obj.gitBranch;
        }
        if (obj.type === 'assistant' && !result.model) {
          result.model = obj.message?.model;
        }
      } catch (e) {
        console.debug('[scanner] Parse error:', (e as Error).message);
      }
    });

    rl.on('close', () => {
      if (!result.firstPrompt && assistantCandidate) result.firstPrompt = assistantCandidate;
      resolve(result);
    });
    rl.on('error', () => resolve(result));
  });
}

async function parseCodexFirstLines(filePath: string): Promise<{
  sessionId?: string;
  firstPrompt?: string;
  cwd?: string;
  model?: string;
  timestamp?: string;
  parentSessionId?: string;
  isSubagent?: boolean;
}> {
  return new Promise((resolve) => {
    const result: any = {};
    let assistantCandidate: string | null = null;
    const stream = fs.createReadStream(filePath, { encoding: 'utf-8' });
    const rl = readline.createInterface({ input: stream });
    let lineCount = 0;

    rl.on('line', (line) => {
      lineCount++;
      if (lineCount > 300) { rl.close(); return; }
      try {
        const obj = JSON.parse(line);

        if (obj.type === 'session_meta' && obj.payload) {
          if (!result.sessionId && typeof obj.payload.id === 'string') {
            result.sessionId = obj.payload.id;
          }
          if (!result.timestamp && typeof obj.payload.timestamp === 'string') {
            result.timestamp = obj.payload.timestamp;
          }
          if (!result.cwd && typeof obj.payload.cwd === 'string') {
            result.cwd = obj.payload.cwd;
          }
          const parentThreadId = obj.payload?.source?.subagent?.thread_spawn?.parent_thread_id;
          if (!result.parentSessionId && typeof parentThreadId === 'string' && parentThreadId.trim()) {
            result.parentSessionId = parentThreadId;
            result.isSubagent = true;
          } else if (!result.parentSessionId && typeof obj.payload.forked_from_id === 'string' && obj.payload.forked_from_id.trim()) {
            result.parentSessionId = obj.payload.forked_from_id;
          }
          return;
        }

        if (!result.sessionId && typeof obj.id === 'string' && obj.timestamp) {
          result.sessionId = obj.id;
          result.timestamp = obj.timestamp;
        }

        const record = obj.type === 'response_item' && obj.payload ? obj.payload : obj;
        if (record.type !== 'message') return;

        const text = extractCodexTextFromContent(record.content);
        if (!result.cwd && text) {
          const cwdMatch = text.match(/<cwd>([\s\S]*?)<\/cwd>/i);
          if (cwdMatch?.[1]) {
            result.cwd = cwdMatch[1].trim();
          }
        }

        if (record.role === 'user' && !result.firstPrompt) {
          const cleaned = cleanCodexPrompt(text);
          if (!isLowSignalPrompt(cleaned)) {
            result.firstPrompt = cleaned!;
          }
        } else if (record.role === 'assistant' && !assistantCandidate) {
          if (!isLowSignalPrompt(text)) assistantCandidate = text!;
        }

        if (!result.model && typeof record.model === 'string') {
          result.model = record.model;
        }
      } catch (e) {
        console.debug('[scanner] Codex parse error:', (e as Error).message);
      }
    });

    rl.on('close', () => {
      if (!result.firstPrompt && assistantCandidate) result.firstPrompt = assistantCandidate;
      resolve(result);
    });
    rl.on('error', () => resolve(result));
  });
}
