import fs from 'fs';
import path from 'path';
import readline from 'readline';
import { PROJECTS_DIR } from '../config.js';
import { getDb } from '../db/connection.js';
import type { SessionIndexEntry } from '../types.js';
import { sanitizeConversationText } from './text-normalization.js';

const LOW_SIGNAL_PROMPT_RE = /^(untitled|no prompt|hi|hello|continue|继续|ok|好的|收到)$/i;
const CAVEAT_PREFIX = 'Caveat: The messages below were generated by the user while running local commands.';

function isLowSignalPrompt(text: string | null | undefined): boolean {
  if (!text) return true;
  const t = text.trim();
  if (!t) return true;
  if (LOW_SIGNAL_PROMPT_RE.test(t)) return true;
  if (t.startsWith(CAVEAT_PREFIX)) return true;
  return false;
}

function extractTextFromContent(content: unknown): string | null {
  if (typeof content === 'string') return sanitizeConversationText(content);
  if (Array.isArray(content)) {
    const joined = content
      .filter((b: any) => b?.type === 'text' && typeof b?.text === 'string')
      .map((b: any) => b.text)
      .join('\n');
    return sanitizeConversationText(joined);
  }
  return null;
}

export async function scanAllProjects(): Promise<number> {
  const db = getDb();
  let count = 0;

  if (!fs.existsSync(PROJECTS_DIR)) return 0;

  const projectDirs = fs.readdirSync(PROJECTS_DIR, { withFileTypes: true })
    .filter(d => d.isDirectory())
    .map(d => d.name);

  const upsert = db.prepare(`
    INSERT INTO sessions (id, project_slug, project_path, summary, first_prompt, message_count,
      git_branch, model, created_at, modified_at, file_path, file_mtime)
    VALUES (@id, @project_slug, @project_path, @summary, @first_prompt, @message_count,
      @git_branch, @model, @created_at, @modified_at, @file_path, @file_mtime)
    ON CONFLICT(id) DO UPDATE SET
      summary = COALESCE(@summary, summary),
      first_prompt = COALESCE(@first_prompt, first_prompt),
      message_count = MAX(COALESCE(@message_count, 0), COALESCE(message_count, 0)),
      git_branch = COALESCE(@git_branch, git_branch),
      model = COALESCE(@model, model),
      project_path = COALESCE(@project_path, project_path),
      modified_at = COALESCE(@modified_at, modified_at),
      file_mtime = COALESCE(@file_mtime, file_mtime)
  `);

  for (const slug of projectDirs) {
    const projectDir = path.join(PROJECTS_DIR, slug);
    const indexPath = path.join(projectDir, 'sessions-index.json');

    // Try sessions-index.json first
    if (fs.existsSync(indexPath)) {
      try {
        const indexData = JSON.parse(fs.readFileSync(indexPath, 'utf-8'));
        const entries: any[] = indexData.entries || [];
        for (const entry of entries) {
          if (entry.isSidechain) continue; // Skip subagent entries
          const filePath = entry.fullPath || path.join(projectDir, `${entry.sessionId}.jsonl`);
          let summary = sanitizeConversationText(entry.summary);
          let firstPrompt = sanitizeConversationText(entry.firstPrompt);
          if (!summary && isLowSignalPrompt(firstPrompt)) {
            const meta = await parseFirstLines(filePath);
            if (!isLowSignalPrompt(meta.firstPrompt)) {
              firstPrompt = meta.firstPrompt!;
            }
          }
          upsert.run({
            id: entry.sessionId,
            project_slug: slug,
            project_path: entry.projectPath || null,
            summary,
            first_prompt: (!isLowSignalPrompt(firstPrompt) ? firstPrompt : null)?.slice(0, 500) || null,
            message_count: entry.messageCount || 0,
            git_branch: entry.gitBranch || null,
            model: null,
            created_at: entry.created || null,
            modified_at: entry.modified || entry.lastModified || null,
            file_path: filePath,
            file_mtime: entry.fileMtime || null,
          });
          count++;
        }
      } catch (e) {
        console.error(`Failed to parse index for ${slug}:`, e);
      }
    }

    // Also scan for .jsonl files not in the index
    const jsonlFiles = fs.readdirSync(projectDir)
      .filter(f => f.endsWith('.jsonl'));

    for (const file of jsonlFiles) {
      const sessionId = path.basename(file, '.jsonl');
      // Check if already in DB
      const existing = db.prepare('SELECT file_mtime FROM sessions WHERE id = ?').get(sessionId) as any;
      const filePath = path.join(projectDir, file);
      const stat = fs.statSync(filePath);
      if (existing && existing.file_mtime >= stat.mtimeMs) continue;
      if (existing) continue; // Already indexed from sessions-index.json

      // Parse first few lines for metadata
      try {
        const meta = await parseFirstLines(filePath);
        upsert.run({
          id: sessionId,
          project_slug: slug,
          project_path: null,
          summary: null,
          first_prompt: sanitizeConversationText(meta.firstPrompt)?.slice(0, 500) || null,
          message_count: 0,
          git_branch: meta.gitBranch || null,
          model: meta.model || null,
          created_at: meta.timestamp || null,
          modified_at: new Date(stat.mtimeMs).toISOString(),
          file_path: filePath,
          file_mtime: stat.mtimeMs,
        });
        count++;
      } catch (e) {
        console.warn('[scanner] Skip file', filePath, ':', (e as Error).message);
      }
    }
  }

  return count;
}

async function parseFirstLines(filePath: string): Promise<{
  firstPrompt?: string; gitBranch?: string; model?: string; timestamp?: string;
}> {
  return new Promise((resolve) => {
    const result: any = {};
    let assistantCandidate: string | null = null;
    const stream = fs.createReadStream(filePath, { encoding: 'utf-8' });
    const rl = readline.createInterface({ input: stream });
    let lineCount = 0;

    rl.on('line', (line) => {
      lineCount++;
      if (lineCount > 200) { rl.close(); return; }
      try {
        const obj = JSON.parse(line);
        if ((obj.type === 'user' || obj.type === 'assistant') && !result.firstPrompt) {
          const text = extractTextFromContent(obj.message?.content);
          if (!isLowSignalPrompt(text)) {
            if (obj.type === 'user') {
              result.firstPrompt = text;
            } else if (!assistantCandidate) {
              assistantCandidate = text!;
            }
          }
          if (!result.timestamp) result.timestamp = obj.timestamp;
          if (!result.gitBranch) result.gitBranch = obj.gitBranch;
        }
        if (obj.type === 'assistant' && !result.model) {
          result.model = obj.message?.model;
        }
      } catch (e) {
        console.debug('[scanner] Parse error:', (e as Error).message);
      }
    });

    rl.on('close', () => {
      if (!result.firstPrompt && assistantCandidate) result.firstPrompt = assistantCandidate;
      resolve(result);
    });
    rl.on('error', () => resolve(result));
  });
}
