import fs from 'fs';
import path from 'path';
import readline from 'readline';
import {
  CODEX_SESSION_INDEX_PATH,
  CODEX_SESSIONS_DIR,
  PROJECTS_DIR,
} from '../config.js';
import { getDb } from '../db/connection.js';
import type { CodexSessionIndexEntry } from '../types.js';
import { sanitizeConversationText } from './text-normalization.js';

const LOW_SIGNAL_PROMPT_RE = /^(untitled|no prompt|hi|hello|continue|缁х画|ok|濂界殑|鏀跺埌)$/i;
const CAVEAT_PREFIX = 'Caveat: The messages below were generated by the user while running local commands.';
const CODEX_ID_PREFIX = 'codex-';

function isLowSignalPrompt(text: string | null | undefined): boolean {
  if (!text) return true;
  const t = text.trim();
  if (!t) return true;
  if (LOW_SIGNAL_PROMPT_RE.test(t)) return true;
  if (t.startsWith(CAVEAT_PREFIX)) return true;
  return false;
}

function extractClaudeTextFromContent(content: unknown): string | null {
  if (typeof content === 'string') return sanitizeConversationText(content);
  if (Array.isArray(content)) {
    const joined = content
      .filter((b: any) => b?.type === 'text' && typeof b?.text === 'string')
      .map((b: any) => b.text)
      .join('\n');
    return sanitizeConversationText(joined);
  }
  return null;
}

function extractCodexTextFromContent(content: unknown): string | null {
  if (!Array.isArray(content)) return null;
  const joined = content
    .filter((b: any) => (b?.type === 'input_text' || b?.type === 'output_text') && typeof b?.text === 'string')
    .map((b: any) => b.text)
    .join('\n');
  return sanitizeConversationText(joined);
}

function cleanCodexPrompt(text: string | null | undefined): string | null {
  if (!text) return null;
  const cleaned = text
    .replace(/<environment_context>[\s\S]*?<\/environment_context>/gi, '')
    .replace(/^# Context from my IDE setup:[\s\S]*?## My request for Codex:\s*/i, '')
    .replace(/^# Context from my IDE setup:[\s\S]*?## My request:\s*/i, '')
    .trim();
  return sanitizeConversationText(cleaned);
}

function slugifyProjectPath(projectPath: string | null | undefined): string {
  if (!projectPath) return 'codex-unknown';
  const slug = projectPath
    .replace(/[:\\/]/g, '-')
    .replace(/\s+/g, '-')
    .replace(/^-+|-+$/g, '');
  return slug || 'codex-unknown';
}

export async function scanAllProjects(): Promise<number> {
  const db = getDb();
  const upsert = db.prepare(`
    INSERT INTO sessions (id, project_slug, project_path, summary, first_prompt, message_count,
      git_branch, model, created_at, modified_at, file_path, file_mtime)
    VALUES (@id, @project_slug, @project_path, @summary, @first_prompt, @message_count,
      @git_branch, @model, @created_at, @modified_at, @file_path, @file_mtime)
    ON CONFLICT(id) DO UPDATE SET
      summary = COALESCE(@summary, summary),
      first_prompt = COALESCE(@first_prompt, first_prompt),
      message_count = MAX(COALESCE(@message_count, 0), COALESCE(message_count, 0)),
      git_branch = COALESCE(@git_branch, git_branch),
      model = COALESCE(@model, model),
      project_path = COALESCE(@project_path, project_path),
      created_at = COALESCE(created_at, @created_at),
      modified_at = COALESCE(@modified_at, modified_at),
      file_path = COALESCE(@file_path, file_path),
      file_mtime = COALESCE(@file_mtime, file_mtime)
  `);

  let count = 0;
  count += await scanClaudeProjects(upsert);
  count += await scanCodexSessions(upsert);
  return count;
}

async function scanClaudeProjects(upsert: any): Promise<number> {
  const db = getDb();
  let count = 0;

  if (!fs.existsSync(PROJECTS_DIR)) return 0;

  const projectDirs = fs.readdirSync(PROJECTS_DIR, { withFileTypes: true })
    .filter(d => d.isDirectory())
    .map(d => d.name);

  for (const slug of projectDirs) {
    const projectDir = path.join(PROJECTS_DIR, slug);
    const indexPath = path.join(projectDir, 'sessions-index.json');

    if (fs.existsSync(indexPath)) {
      try {
        const indexData = JSON.parse(fs.readFileSync(indexPath, 'utf-8'));
        const entries: any[] = indexData.entries || [];
        for (const entry of entries) {
          if (entry.isSidechain) continue;
          const filePath = entry.fullPath || path.join(projectDir, `${entry.sessionId}.jsonl`);
          let summary = sanitizeConversationText(entry.summary);
          let firstPrompt = sanitizeConversationText(entry.firstPrompt);
          if (!summary && isLowSignalPrompt(firstPrompt)) {
            const meta = await parseClaudeFirstLines(filePath);
            if (!isLowSignalPrompt(meta.firstPrompt)) {
              firstPrompt = meta.firstPrompt!;
            }
          }
          upsert.run({
            id: entry.sessionId,
            project_slug: slug,
            project_path: entry.projectPath || null,
            summary,
            first_prompt: (!isLowSignalPrompt(firstPrompt) ? firstPrompt : null)?.slice(0, 500) || null,
            message_count: entry.messageCount || 0,
            git_branch: entry.gitBranch || null,
            model: null,
            created_at: entry.created || null,
            modified_at: entry.modified || entry.lastModified || null,
            file_path: filePath,
            file_mtime: entry.fileMtime || null,
          });
          count++;
        }
      } catch (e) {
        console.error(`Failed to parse index for ${slug}:`, e);
      }
    }

    const jsonlFiles = fs.readdirSync(projectDir).filter(f => f.endsWith('.jsonl'));
    for (const file of jsonlFiles) {
      const sessionId = path.basename(file, '.jsonl');
      const existing = db.prepare('SELECT file_mtime FROM sessions WHERE id = ?').get(sessionId) as any;
      const filePath = path.join(projectDir, file);
      const stat = fs.statSync(filePath);
      if (existing && existing.file_mtime >= stat.mtimeMs) continue;
      if (existing) continue;

      try {
        const meta = await parseClaudeFirstLines(filePath);
        upsert.run({
          id: sessionId,
          project_slug: slug,
          project_path: null,
          summary: null,
          first_prompt: sanitizeConversationText(meta.firstPrompt)?.slice(0, 500) || null,
          message_count: 0,
          git_branch: meta.gitBranch || null,
          model: meta.model || null,
          created_at: meta.timestamp || null,
          modified_at: new Date(stat.mtimeMs).toISOString(),
          file_path: filePath,
          file_mtime: stat.mtimeMs,
        });
        count++;
      } catch (e) {
        console.warn('[scanner] Skip file', filePath, ':', (e as Error).message);
      }
    }
  }

  return count;
}

async function scanCodexSessions(upsert: any): Promise<number> {
  const db = getDb();
  let count = 0;

  if (!fs.existsSync(CODEX_SESSIONS_DIR)) return 0;

  const indexMap = readCodexSessionIndex();
  const files = listJsonlFiles(CODEX_SESSIONS_DIR);

  for (const filePath of files) {
    try {
      const meta = await parseCodexFirstLines(filePath);
      if (!meta.sessionId) continue;

      const sessionId = `${CODEX_ID_PREFIX}${meta.sessionId}`;
      const stat = fs.statSync(filePath);
      const existing = db.prepare('SELECT file_mtime FROM sessions WHERE id = ?').get(sessionId) as any;
      if (existing && existing.file_mtime >= stat.mtimeMs) continue;

      const indexEntry = indexMap.get(meta.sessionId);
      const summary = sanitizeConversationText(indexEntry?.thread_name || null);
      const projectPath = meta.cwd || null;

      upsert.run({
        id: sessionId,
        project_slug: slugifyProjectPath(projectPath),
        project_path: projectPath,
        summary,
        first_prompt: (!isLowSignalPrompt(meta.firstPrompt) ? meta.firstPrompt : null)?.slice(0, 500) || null,
        message_count: 0,
        git_branch: null,
        model: meta.model || null,
        created_at: meta.timestamp || null,
        modified_at: indexEntry?.updated_at || new Date(stat.mtimeMs).toISOString(),
        file_path: filePath,
        file_mtime: stat.mtimeMs,
      });
      count++;
    } catch (e) {
      console.warn('[scanner] Skip Codex session', filePath, ':', (e as Error).message);
    }
  }

  return count;
}

function listJsonlFiles(root: string): string[] {
  const results: string[] = [];
  const stack = [root];

  while (stack.length > 0) {
    const current = stack.pop()!;
    const entries = fs.readdirSync(current, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = path.join(current, entry.name);
      if (entry.isDirectory()) {
        stack.push(fullPath);
      } else if (entry.isFile() && entry.name.endsWith('.jsonl')) {
        results.push(fullPath);
      }
    }
  }

  return results;
}

function readCodexSessionIndex(): Map<string, CodexSessionIndexEntry> {
  const indexMap = new Map<string, CodexSessionIndexEntry>();
  if (!fs.existsSync(CODEX_SESSION_INDEX_PATH)) return indexMap;

  const lines = fs.readFileSync(CODEX_SESSION_INDEX_PATH, 'utf-8').split(/\r?\n/).filter(Boolean);
  for (const line of lines) {
    try {
      const entry = JSON.parse(line) as CodexSessionIndexEntry;
      if (typeof entry.id === 'string' && entry.id.trim()) {
        indexMap.set(entry.id, entry);
      }
    } catch {
      // ignore malformed index lines
    }
  }

  return indexMap;
}

async function parseClaudeFirstLines(filePath: string): Promise<{
  firstPrompt?: string; gitBranch?: string; model?: string; timestamp?: string;
}> {
  return new Promise((resolve) => {
    const result: any = {};
    let assistantCandidate: string | null = null;
    const stream = fs.createReadStream(filePath, { encoding: 'utf-8' });
    const rl = readline.createInterface({ input: stream });
    let lineCount = 0;

    rl.on('line', (line) => {
      lineCount++;
      if (lineCount > 200) { rl.close(); return; }
      try {
        const obj = JSON.parse(line);
        if ((obj.type === 'user' || obj.type === 'assistant') && !result.firstPrompt) {
          const text = extractClaudeTextFromContent(obj.message?.content);
          if (!isLowSignalPrompt(text)) {
            if (obj.type === 'user') {
              result.firstPrompt = text;
            } else if (!assistantCandidate) {
              assistantCandidate = text!;
            }
          }
          if (!result.timestamp) result.timestamp = obj.timestamp;
          if (!result.gitBranch) result.gitBranch = obj.gitBranch;
        }
        if (obj.type === 'assistant' && !result.model) {
          result.model = obj.message?.model;
        }
      } catch (e) {
        console.debug('[scanner] Parse error:', (e as Error).message);
      }
    });

    rl.on('close', () => {
      if (!result.firstPrompt && assistantCandidate) result.firstPrompt = assistantCandidate;
      resolve(result);
    });
    rl.on('error', () => resolve(result));
  });
}

async function parseCodexFirstLines(filePath: string): Promise<{
  sessionId?: string; firstPrompt?: string; cwd?: string; model?: string; timestamp?: string;
}> {
  return new Promise((resolve) => {
    const result: any = {};
    let assistantCandidate: string | null = null;
    const stream = fs.createReadStream(filePath, { encoding: 'utf-8' });
    const rl = readline.createInterface({ input: stream });
    let lineCount = 0;

    rl.on('line', (line) => {
      lineCount++;
      if (lineCount > 300) { rl.close(); return; }
      try {
        const obj = JSON.parse(line);

        if (obj.type === 'session_meta' && obj.payload) {
          if (!result.sessionId && typeof obj.payload.id === 'string') {
            result.sessionId = obj.payload.id;
          }
          if (!result.timestamp && typeof obj.payload.timestamp === 'string') {
            result.timestamp = obj.payload.timestamp;
          }
          if (!result.cwd && typeof obj.payload.cwd === 'string') {
            result.cwd = obj.payload.cwd;
          }
          return;
        }

        if (!result.sessionId && typeof obj.id === 'string' && obj.timestamp) {
          result.sessionId = obj.id;
          result.timestamp = obj.timestamp;
        }

        const record = obj.type === 'response_item' && obj.payload ? obj.payload : obj;
        if (record.type !== 'message') return;

        const text = extractCodexTextFromContent(record.content);
        if (!result.cwd && text) {
          const cwdMatch = text.match(/<cwd>([\s\S]*?)<\/cwd>/i);
          if (cwdMatch?.[1]) {
            result.cwd = cwdMatch[1].trim();
          }
        }

        if (record.role === 'user' && !result.firstPrompt) {
          const cleaned = cleanCodexPrompt(text);
          if (!isLowSignalPrompt(cleaned)) {
            result.firstPrompt = cleaned!;
          }
        } else if (record.role === 'assistant' && !assistantCandidate) {
          if (!isLowSignalPrompt(text)) assistantCandidate = text!;
        }

        if (!result.model && typeof record.model === 'string') {
          result.model = record.model;
        }
      } catch (e) {
        console.debug('[scanner] Codex parse error:', (e as Error).message);
      }
    });

    rl.on('close', () => {
      if (!result.firstPrompt && assistantCandidate) result.firstPrompt = assistantCandidate;
      resolve(result);
    });
    rl.on('error', () => resolve(result));
  });
}
